GraphQLAdapterLocation: "https://github.com/rossbelmont/graphql-impl-guide-sf-connect/raw/main/graphql.resolvers.sql-1.0.0.jar"
GraphQLAdapterName: "graphql.resolvers.sql-1.0.0.jar"
GraphQLSchemaLocation: "https://raw.githubusercontent.com/rossbelmont/graphql-impl-guide-sf-connect/main/postgres-schema.graphql"
GraphQLSchemaName: "postgres-schema.graphql"
RDSSchemaLocation: "https://raw.githubusercontent.com/rossbelmont/graphql-impl-guide-sf-connect/main/postgres-ddl.sql"
RDSSchemaName: "postgres-ddl.sql"
